- Dockerfile
- publisher/publisher.go
> refactor: dockerfile cleanup

- Dockerfile
- publisher/publisher.go
- schemas/nrjmx.yml
- schemas/ohi.yml
This PR:
- fix mirroring
- refactor code a bit to unify loops
- adds timeout for commands
> feat(mirror): fix apt mirror and refactor code

- .github/workflows/security.yml
> feat(action): fix snyk

- .github/workflows/test.yml
- action.yml
- publisher/publisher.go
Use a different bucket for exclusively for locks.
> feat(lock): lockfiles within exclusive bucket

- scripts/Makefile
> AWS STS credentials goofys

- Dockerfile
- README.md
- action-run.sh
- action.yml
- publisher/lock/s3_lock_test.go
- publisher/publisher.go
- schemas/ohi.yml
- scripts/Makefile
AWS STS service account (token based) credentials for `s3fs`.
Issue detail at https://github.com/s3fs-fuse/s3fs-fuse/issues/651#issuecomment-561111268
---
Also renamed AWS_ACCESS_KEY input to AWS_ACCESS_KEY_ID standard.
> Token based credentials

- scripts/Makefile
- refactor: cleanup
- ci: debug
> feat troubleshoot

- scripts/Makefile
- refactor: cleanup
- ci: debug
- fix: passing aws_region
> feat troubleshoot region

- publisher/publisher.go
- publisher/publisher_test.go
Details https://github.com/newrelic/infrastructure-agent/runs/2006043151?check_suite_focus=true
> fix: download os-version

- publisher/publisher.go
Update RPM architecture variable replacement to match package managers value expectations on ARM values.
There's no official docs on the RPM manual regarding these values.
https://docs.fedoraproject.org/en-US/Fedora/15/html/Deployment_Guide/sec-Using_Yum_Variables.html
> fix: RPM ARM architecture variables

- publisher/publisher.go
- schemas/e2e.yml
- test/publish-agent.sh
Added assertions for all distributed platforms.
> test: assert files exist for all platforms in e2e

- schemas/ohi.yml
Add ARM packages to the RPM repos
> Add ARM support for the integrations

- schemas/ohi-jmx.yml
- Add ARM for JMX integrations.
> Add ARM support for the JMX integrations

- schemas/nrjmx.yml
> ci: updated nrjmx schema

- publisher/publisher.go
- schemas/nrjmx.yml
- schemas/ohi-jmx.yml
- schemas/ohi.yml
**Versions to be added**
* Ubuntu
* 20.10 (groovy)
* 21.04 (Hirsute Hippo)
* Debian
* 11 (bullseye)
* SUSE 
* 12.15
* 15.1
* 15.2 
* 15.3
* Oracle Linux (same versions as RHEL)
* 7
* 8
> feat(new_os_versions): add new OS versions to OHIs publish schemas

- Makefile
- scripts/recreate-tag.sh
make target to recreate v1 tag pointing to current main branch
> feat: make target to recreate v1 tag from main

- action-run.sh
- scripts/Makefile
It is better to check right after the execution in the container itself
> feat(log): logging remaining space in container

- schemas/nrjmx.yml
- schemas/ohi-jmx.yml
- schemas/ohi.yml
> feat: add ubuntu 24 to ohi schemas (NR-248002)

- publisher/upload/upload.go
This PR adds retries to `aptly mirror update`
> feat: add retries to aptly mirror update

- schemas/nrjmx-fips.yml
- schemas/nrjmx.yml
- schemas/ohi-fips.yml
- schemas/ohi-jmx-fips.yml
- schemas/ohi-jmx.yml
- schemas/ohi.yml
Added support for RHEL 10 to the publish schemas.
> NR-423018: RHEL 10 support

- schemas/nrjmx-fips.yml
- schemas/nrjmx.yml
- schemas/ohi-fips.yml
- schemas/ohi-jmx-fips.yml
- schemas/ohi-jmx.yml
- schemas/ohi.yml
Reverts newrelic/infrastructure-publish-action#181
> Revert "NR-423018: RHEL 10 support"

- schemas/nrjmx-fips.yml
- schemas/nrjmx.yml
- schemas/ohi-fips.yml
- schemas/ohi-jmx-fips.yml
- schemas/ohi-jmx.yml
- schemas/ohi.yml
Reverts newrelic/infrastructure-publish-action#182
> Revert "Revert "NR-423018: RHEL 10 support""
