- publisher/publisher.go
- publisher/publisher_test.go
Fixes error trying to read stdout/stderr when cmd start fails. It check cmd start error before triggering streamAsLog on stdout/err.
It also waits for streams to be handled until exiting.
> fix: check cmd start error before triggering streamAsLog on stdout/err

- action-run.sh
- action.yml
- publisher/publisher.go
- scripts/Makefile
GPG key name is not really required. We only import one key to the keyring and so this one key will be used with aptly.
Removing the key name removes another secret that we have to maintain and simplifies things a bit.
> remove not required gpg key name

- .github/workflows/test.yml
- action.yml
- publisher/publisher.go
Add run ID, to owner data, so different runs won't clash and triggering actor could be identified.
This value could be provided from GHA `GITHUB_RUN_ID` env-var https://docs.github.com/en/actions/reference/environment-variables
> feat(lock): add run-id to owner

- .github/workflows/test.yml
- action.yml
- publisher/lock/s3_lock.go
- publisher/publisher.go
Disable to manage leftover lockfiles manually for now, people want to use leftovers as smoke signal of potentially corrupted repos.
> feat lock disable ttl

- Dockerfile
Use "quiet" options for curl, wget and unzip to not spam the logs with unimportant logs
> Reduce output from wget, curl and unzip

- action.yml
There's not default and in the publisher we expect some value, so best to put a default here
> Set default "false" in disable-lock

- scripts/Makefile
We no longer prefix repo folders as environments are split among different buckets.
> fix: remove test prefix

- schemas/ohi-jmx.yml
We have refactored the windows intaller of integrations that uses nrjmx to bundle it in the installer. 
These change has involved a renaming and extension type modification. 
The PR adds these schema to be used by these integrations (kafka, cassandra )
> feat: add schema of integrations bundling nrjmx in windows installer

- publisher/lock/s3_lock.go
Replace goto with for as requested https://github.com/newrelic/infrastructure-publish-action/pull/83#discussion_r607671794
I still think this is one of the few legit usages of goto, making the code more readable in this case.
wdyt?
> refactor: replace goto with for

- publisher/publisher.go
Retrieve args from env, as it's done for CLI
> fix: missing env-vars

- publisher/publisher.go
Don't rely on .repo file in repository. Always recreate with specified `accessPointHost`.
> fix: always generate rpm .repo file

- Dockerfile
Changing docker image for the running action from `debian buster` to `centos-8` in order to use a more up-to-date version of `createrepo`
The version distributed in `debian buster` doesn't support weak dependencies for rpm.
> feature: use centos-8 docker image for action container

- schemas/nrjmx.yml
- schemas/ohi-jmx.yml
- schemas/ohi.yml
Change integrations Amazon Linux 2 repository as infrastructure-agent repository location for Amazon Linux 2 is going to be changed.
> feat: separate Amazon Linux 2 repository for integrations

- README.md
- action-run.sh
- action.yml
- publisher/publisher.go
- publisher/publisher_test.go
Currently the `{version}` from the `tag` parameter (removing the trailing v ) which works when the `tag` only contains version.
This PR adds an optional parameter to the publish action called `app_version` which if existed will be used as the `{version}`, if not, the same behavior remains.
FIX: This PR also introduces a Fix for the `lock_group` which was not being set from Environment variables
> feat: add app_version parameter

- publisher/upload/upload.go
- publisher/upload/upload_test.go
- Return error when one arch fails directly. The error was getting overwritten if there were more archs to compute and suceeded.
> Assert error doesn't get overwritten and is returned when one arch fails to get published

- README.md
- action-run.sh
- action.yml
- scripts/Makefile
We have a monorepo where the upload schema can change from one integration to another so we generate the upload schema per integration on each release using a template.
This action only supports setting the schema using a URL, so I added the possibility of adding the schema using a path.
I also changed a few aspects of the script:
* `iptables` rules are only set if you are running inside the CI
* Added a `"$@"` at the end of the script to allow local/PR testing. It is not populated in the `action.yml` so there is no possiblity of us abusing it in the pipelines.
* Allow to run the action script in our new M1s locally. `publisher.go` refused so compile in an ARM processor:
```
=> CACHED [13/23] WORKDIR /home/gha/publisher …
```
> Add custom-local schema

- test/publish-agent.sh
In the last PR (#142) I modified the script to only apply `iptables` rules inside the CI so we can run the action locally to test things.
I did not modify the e2e script that calls the script explicitly so the e2e is unreliable and it failed the last CI run.
This should fix the issue.
> Make e2e test more reliable

- action-run.sh
Deleting some unused software frees up 25GB allowing us to buy some time in order to understand how quickly we should fix the issue.
Notice that it is a workaround proposed by some GitHub runners maintainers in a couple of issues
> Deleting unused software from githubRunner to free up space

- schemas/ohi-fips.yml
- schemas/ohi.yml
We need to publish FIPS packages in addition to the existing packages. Therefore, update the schema for s3 upload.
[S3 after prerelease run with this schema for nri-redis](http://nr-downloads-ohai-staging.s3-website-us-east-1.amazonaws.com/rohan-fips-test-redis/)
***Note:*** ~This is a breaking change until all OHIs are updated to have FIPS packages.~
> add fips upload schemas to ohi.yml

- schemas/ohi-jmx-fips.yml
It is almost the same as `ohi-jmx` schema, but with support only for linux amd64 and linux arm64.
> feat(fips): add ohi jmx fips schema

- publisher/upload/upload.go
`aptly mirror update` seems to continue failing even if `-max-tries` is present:
https://github.com/newrelic/nri-mysql/actions/runs/13156763333/job/36715558791
This PR adds retries in shell level as `aptly mirror update` is idempotent
> feat: retry if deb mirror update fails

- publisher/config/schema.go
- publisher/config/schema_test.go
- publisher/publisher.go
- publisher/upload/upload.go
`APP_NAME` and artifact name should match or at least the package name should have `APP_NAME` as prefix. 
Explanation:
The action will receive the next parameters, among others:
* src: some-package-name-1.2.3-any.deb
* `APP_NAME`: some-package-name
Based on these parameters, the artifact will be uploaded to:
```
└── infrastructure_agent
└── linux
└── apt
├── dists
│   └── noble
│       ├── Contents-amd64.gz
│       ├── InRelease
│       ├── main
│       │   ├── binary-amd64
│       │   │   ├── Packages
│       │   │   ├── Packages.bz2
│       │   │   ├── Packages.gz
│       │   │   └── Release
│       │   └── Contents-amd64.gz
│       ├── Release
│       └── Release.gpg
└── pool
└── main
└── s
└── some-package-name
└── some-package-name-1.2.3-any.deb
```
Where:
*  `s` is retrieved by the …
> feat: validate app name is consistent with pkg name

- README.md
- publisher/config/config.go
- publisher/go.mod
- publisher/go.sum
- publisher/publisher.go
- publisher/release/marker.go
- publisher/release/marker_aws.go
- publisher/release/marker_aws_test.go
- publisher/upload/upload.go
- publisher/upload/upload_test.go
This PR will add release information to a file in the bucket where the package is being released.
After the lock is executed, an entry with start time will be appended to `repo_path_root_dir/releases.json`.
Just before the lock is released the entry will be loaded, end time will be set, and file will be persisted.
Example of data persisted:
```
[
{
"app_name": "newrelic-infra",
"tag": "1.7.0",
"run_id": "13549016185",
"start": "2025-02-26T16:57:33Z",
"end": "2025-02-26T16:58:47Z",
"repo_name": "newrelic/infrastructure-agent",
"schema": "custom",
"schema_url": "https://raw.githubusercontent.com/newrelic/infrastructure-agent/test_publish_action_markers/build/upload-schema-linux-deb.yml"
},
{
"app_name": "newrelic-infra",
"tag": "1.7.0",
"run_id": "13549016185",
"start": …
```
> feat: add release markers

- publisher/download/download.go
- publisher/utils/utils.go
- publisher/utils/utils_test.go
This PR adds retries to GH asset download process. 
The latest release failed because of it:
```
[✔] Download https://github.com/newrelic/infrastructure-agent/releases/download/1.62.0/newrelic-infra-1.62.0-1.sles12.2.arm.rpm.sum into /home/gha/assets/newrelic-infra-1.62.0-1.sles12.2.arm.rpm.sum 107 bytes
Starting downloading artifacts!
[ ] Download https://github.com/newrelic/infrastructure-agent/releases/download/1.62.0/newrelic-infra-1.62.0-1.sles12.3.arm.rpm.sum into /home/gha/assets/newrelic-infra-1.62.0-1.sles12.3.arm.rpm.sum
error on download https://github.com/newrelic/infrastructure-agent/releases/download/1.62.0/newrelic-infra-1.62.0-1.sles12.3.arm.rpm.sum with status code 403
make: *** [Makefile:69: publish-artifacts] Error 1
Error: Process completed with exit code 2.
```
> feat: add retries to GH asset download

- schemas/nrjmx-fips.yml
Added FIPS schema for nrjmx.
The filenames to be supported are:
[nrjmx-fips-2.7.1-1.noarch.rpm](https://github.com/newrelic/nrjmx/releases/download/v2.7.1/nrjmx-fips-2.7.1-1.noarch.rpm)
[nrjmx-fips_2.7.1-1_noarch.deb](https://github.com/newrelic/nrjmx/releases/download/v2.7.1/nrjmx-fips_2.7.1-1_noarch.deb)
[nrjmx_linux-fips_2.7.1_noarch.tar.gz](https://github.com/newrelic/nrjmx/releases/download/v2.7.1/nrjmx_linux-fips_2.7.1_noarch.tar.gz)
> Added nrjmx-fips schema

- schemas/nrjmx.yml
- schemas/ohi-fips.yml
- schemas/ohi-jmx-fips.yml
- schemas/ohi-jmx.yml
- schemas/ohi.yml
Added support for SLES 15.6 to the publish schemas.
Refer to this commit for context on a similar task
https://github.com/newrelic/infrastructure-publish-action/commit/d953e9b5655e28b0def3b1b452e819d0c0b199cb
> SLES 15.6 support
